#!/usr/bin/env python3
"""
build_report_html.py — 日次学習レポートを「自己完結 HTML」に変換する。

使い方:
    python3 scripts/build_report_html.py [YYYY-MM-DD]   # 指定日（省略時はローカル今日）
    python3 scripts/build_report_html.py --all          # 既存の全レポートを再生成（バックフィル）

挙動:
- `_integrations/<date>_*.md`（統合レポート）と `domains/<分野>/<date>_*.md`（各ドメイン全文）
  を読み込み、`docs/reports/<date>.html` を生成する。
- 各ドメインの「今日のテーマ概要」カード自体が <details>（折りたたみ）で、クリックすると
  そのドメインの全文 markdown がレンダリングされて開く。ローカルの .md は一切変更しない。
- CSS は `docs/style.css` をインライン展開するので、生成 HTML は単体でも開ける／共有できる。
- `docs/index.html` を再生成し、`docs/reports/` に既に存在するレポートのナビ（前日/翌日）も
  整合するよう貼り直す（過去 .md の一括 HTML 化はしない＝既存 .html があるものだけ）。

依存: 標準ライブラリ + `markdown`（`pip install markdown` / 既存環境では導入済み）。
"""
from __future__ import annotations

import datetime as _dt
import html
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

try:
    import markdown as _markdown
except ImportError:  # pragma: no cover
    sys.exit("エラー: Python の markdown ライブラリが必要です（pip install markdown）。")

# --- パス定義 ----------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
INTEGRATIONS_DIR = ROOT / "_integrations"
DOMAINS_DIR = ROOT / "domains"
DOCS_DIR = ROOT / "docs"
REPORTS_DIR = DOCS_DIR / "reports"
STYLE_CSS = DOCS_DIR / "style.css"

GITHUB_BLOB = "https://github.com/YamamotoNaoyuki/DailyLearning/blob/main"
GENERATED_BY = "Generated by 知識統合システム"

# (フォルダ名, バッジ表示名, CSS サフィックス, アクション節用の日本語名)
DOMAINS: List[Tuple[str, str, str, str]] = [
    ("tech", "tech", "tech", "テクノロジー"),
    ("music", "music", "music", "音楽"),
    ("piano", "piano", "piano", "ピアノ"),
    ("golf", "golf", "golf", "ゴルフ"),
    ("anatomy", "anatomy", "anatomy", "解剖学"),
    ("bread", "bread", "bread", "パン"),
    ("cs", "cs", "cs", "CS"),
    ("house-hunting", "house", "house-hunting", "家探し"),
    ("deutsch", "deutsch", "deutsch", "ドイツ語"),
    ("other", "other", "other", "その他"),
]
DOMAIN_KEYS = [d[0] for d in DOMAINS]
DOMAIN_LABEL = {d[0]: d[1] for d in DOMAINS}
DOMAIN_CSS = {d[0]: d[2] for d in DOMAINS}
DOMAIN_JP = {d[0]: d[3] for d in DOMAINS}

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
MD_EXTENSIONS = ["tables", "fenced_code", "attr_list", "nl2br"]

_LIST_ITEM_RE = re.compile(r"^ {0,3}(?:[-*+]|\d+[.)])\s+\S")
_FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")


def loosen_lists(text: str) -> str:
    """箇条書きの直前に空行を補う。

    `/learn` の出力は `説明文:` の直後に空行なしで `- 項目` を続けることが多く、
    Python-Markdown はそれをリストと認識しない（段落の続きの平文になる）。
    フェンスコードブロックの中は対象外。
    """
    out: List[str] = []
    in_fence = False
    fence_char = ""
    for ln in text.split("\n"):
        mf = _FENCE_RE.match(ln)
        if mf:
            if not in_fence:
                in_fence, fence_char = True, mf.group(1)[0]
            elif ln.strip().startswith(fence_char * 3):
                in_fence = False
            out.append(ln)
            continue
        if (not in_fence) and out and _LIST_ITEM_RE.match(ln):
            prev = out[-1]
            if prev.strip() and not _LIST_ITEM_RE.match(prev) and not prev.startswith((" ", "\t")):
                out.append("")
        out.append(ln)
    return "\n".join(out)


# --- markdown レンダリング ---------------------------------------------------
def md_html(text: str) -> str:
    """ブロックレベルの markdown → HTML。"""
    return _markdown.markdown(loosen_lists(text or ""), extensions=MD_EXTENSIONS, output_format="html")


def md_inline(text: str) -> str:
    """1 行ぶんの markdown をインライン HTML に（外側の <p> を剥がす）。"""
    out = md_html(text).strip()
    m = re.match(r"^<p>(.*)</p>$", out, re.S)
    return (m.group(1) if m else out).strip()


def esc(text: str) -> str:
    return html.escape(text, quote=True)


# --- ファイル探索 ------------------------------------------------------------
def normalize_domain_key(raw: str) -> Optional[str]:
    key = raw.strip().lower()
    if key in DOMAIN_KEYS:
        return key
    for k in DOMAIN_KEYS:
        if k == key or k.startswith(key) or key.startswith(k):
            return k
        if DOMAIN_LABEL[k] == key or DOMAIN_JP[k] == raw.strip():
            return k
    return None


def find_domain_entry(domain: str, date: str) -> Optional[Path]:
    d = DOMAINS_DIR / domain
    if not d.is_dir():
        return None
    cands = sorted(p for p in d.glob(f"{date}_*.md") if p.name != "_summary.md")
    return cands[0] if cands else None


def find_integration(date: str) -> Optional[Path]:
    if not INTEGRATIONS_DIR.is_dir():
        return None
    cands = sorted(INTEGRATIONS_DIR.glob(f"{date}_*.md"))
    # 数字サフィックス（_2 等）が付かないものを優先
    cands.sort(key=lambda p: (re.search(r"_\d+\.md$", p.name) is not None, p.name))
    return cands[0] if cands else None


def existing_report_dates() -> List[str]:
    if not REPORTS_DIR.is_dir():
        return []
    out = []
    for p in REPORTS_DIR.glob("*.html"):
        m = DATE_RE.match(p.stem)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


def all_integration_dates() -> List[str]:
    if not INTEGRATIONS_DIR.is_dir():
        return []
    out = []
    for p in INTEGRATIONS_DIR.glob("*.md"):
        m = DATE_RE.match(p.name)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


# --- 統合レポートのパース ----------------------------------------------------
def split_h1_sections(md_text: str) -> Tuple[str, List[Tuple[str, str]], str]:
    """`# H1` と `## セクション` で分割。戻り値 (h1, [(heading, body)], footer_text)。"""
    lines = md_text.splitlines()
    h1 = ""
    # 先頭の H1 を取り出す
    for idx, ln in enumerate(lines):
        if ln.startswith("# "):
            h1 = ln[2:].strip()
            lines = lines[idx + 1:]
            break
    sections: List[Tuple[str, str]] = []
    head: Optional[str] = None
    buf: List[str] = []
    for ln in lines:
        if ln.startswith("## "):
            if head is not None:
                sections.append((head, "\n".join(buf).strip()))
            head = ln[3:].strip()
            buf = []
        else:
            buf.append(ln)
    if head is not None:
        sections.append((head, "\n".join(buf).strip()))
    # フッター（最後のセクション本文末尾の "*Generated by ...*" や "---"）はそのまま本文に残し、
    # 出力時に固定フッターを別途付ける。ここでは footer は空文字を返す。
    return h1, sections, ""


def split_subsections(body: str) -> List[Tuple[str, str]]:
    """`### サブ見出し` で分割。先頭の前文は ("", text)。空のエントリは除く。"""
    out: List[Tuple[str, str]] = []
    head = ""
    buf: List[str] = []
    for ln in body.splitlines():
        if ln.startswith("### "):
            if head or "".join(buf).strip():
                out.append((head, "\n".join(buf).strip()))
            head = ln[4:].strip()
            buf = []
        else:
            buf.append(ln)
    if head or "".join(buf).strip():
        out.append((head, "\n".join(buf).strip()))
    return [(h, b) for (h, b) in out if h or b]


def strip_trailing_meta(body: str) -> str:
    """セクション本文末尾の "---" / "*Generated by ...*" を取り除く。"""
    lines = body.splitlines()
    while lines:
        s = lines[-1].strip()
        if s == "" or s == "---" or re.match(r"^\*.*知識統合システム.*\*$", s) or re.match(r"^_.*知識統合システム.*_$", s):
            lines.pop()
        else:
            break
    return "\n".join(lines).strip()


def parse_theme_overview(body: str) -> Dict[str, str]:
    """`- **domain**: text` の箇条書きを {domain_key: abstract_html} に。"""
    result: Dict[str, str] = {}
    for ln in body.splitlines():
        m = re.match(r"^\s*[-*]\s+\*\*([^*]+)\*\*\s*[:：]\s*(.+?)\s*$", ln)
        if not m:
            continue
        key = normalize_domain_key(m.group(1))
        if key:
            result[key] = md_inline(m.group(2))
    return result


def parse_topic_table(body: str) -> List[Tuple[str, str, str]]:
    """markdown テーブル → [(domain_key_or_raw, theme_text, github_link)]。"""
    rows: List[Tuple[str, str, str]] = []
    for ln in body.splitlines():
        ln = ln.strip()
        if not ln.startswith("|"):
            continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) < 2:
            continue
        joined = "".join(cells)
        if joined and set(joined) <= set("-:| "):  # 区切り行
            continue
        if cells[0] in ("分野", "domain", "Domain", "Field"):  # ヘッダ行
            continue
        domain_raw = cells[0]
        theme = cells[1]
        link = ""
        for cell in cells[2:]:
            m = re.search(r"\((https?://[^)]+)\)", cell)
            if m:
                link = m.group(1)
                break
        if not link:
            m = re.search(r"\[([^\]]+)\]\((https?://[^)]+)\)", theme)
            if m:
                theme = m.group(1).strip()
                link = m.group(2)
        # テーマ列に残った markdown リンク記法を平文化
        theme = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", theme).strip()
        key = normalize_domain_key(domain_raw) or domain_raw.lower()
        rows.append((key, theme, link))
    return rows


# --- ドメインエントリのパース ------------------------------------------------
def parse_domain_entry(path: Path) -> Tuple[str, List[str], str]:
    """ドメイン .md → (title, tags, body_html)。先頭の H1 とメタ行（日付/分野/タグ）を除く。"""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    title = path.stem
    tags: List[str] = []
    i = 0
    n = len(lines)
    # H1
    while i < n and lines[i].strip() == "":
        i += 1
    if i < n and lines[i].lstrip().startswith("# "):
        title = lines[i].lstrip()[2:].strip()
        i += 1
    # メタ行（**日付**:, **分野**:, **タグ**:）と空行をスキップ
    while i < n:
        s = lines[i].strip()
        if s == "":
            i += 1
            continue
        mm = re.match(r"^\*\*\s*(日付|分野|タグ|tags?|date|domain)\s*\*\*\s*[:：]", s)
        if mm:
            if "タグ" in s or s.lower().startswith("**tag"):
                tags = re.findall(r"#\S+", s)
            i += 1
            continue
        break
    body_md = "\n".join(lines[i:]).strip()
    return title, tags, md_html(body_md)


# --- HTML 部品 ---------------------------------------------------------------
def badge(domain_key: str) -> str:
    css = DOMAIN_CSS.get(domain_key, domain_key)
    label = DOMAIN_LABEL.get(domain_key, domain_key)
    return f'<span class="badge badge-{css}">{esc(label)}</span>'


def github_link_for_entry(entry: Path) -> str:
    rel = entry.relative_to(ROOT).as_posix()
    return f"{GITHUB_BLOB}/{rel}"


def render_topic_table(rows: List[Tuple[str, str, str]]) -> str:
    if not rows:
        return ""
    body_rows = []
    for key, theme, link in rows:
        in_page = key in DOMAIN_KEYS
        theme_cell = (
            f'<a href="#card-{key}">{esc(theme)}</a>' if in_page else esc(theme)
        )
        src_cell = (
            f'<a href="{esc(link)}" class="ext-link" target="_blank" rel="noopener">md&nbsp;↗</a>'
            if link else ""
        )
        b = badge(key) if in_page else f'<span class="badge badge-other">{esc(key)}</span>'
        body_rows.append(
            f"          <tr><td>{b}</td><td>{theme_cell}</td><td class=\"src-col\">{src_cell}</td></tr>"
        )
    return (
        '    <section class="section" id="topics">\n'
        '      <h2 class="section-title">今日のトピック一覧</h2>\n'
        '      <table class="topic-table">\n'
        "        <thead><tr><th>分野</th><th>テーマ</th><th></th></tr></thead>\n"
        "        <tbody>\n" + "\n".join(body_rows) + "\n        </tbody>\n"
        "      </table>\n"
        "    </section>\n"
    )


def render_domain_cards(theme_overview: Dict[str, str], topic_links: Dict[str, str], date: str) -> str:
    cards = []
    for key in DOMAIN_KEYS:
        entry = find_domain_entry(key, date)
        if entry is None:
            continue
        title, tags, body_html = parse_domain_entry(entry)
        link = topic_links.get(key) or github_link_for_entry(entry)
        css = DOMAIN_CSS[key]
        abstract = theme_overview.get(key, "")
        abstract_block = (
            f'\n          <span class="card-abstract">{abstract}</span>' if abstract else ""
        )
        tag_block = ""
        if tags:
            tag_block = (
                '          <div class="domain-tags">'
                + " ".join(f'<span class="tag">{esc(t)}</span>' for t in tags)
                + "</div>\n"
            )
        cards.append(
            f'      <details id="card-{key}" class="card card-{css} domain-details">\n'
            f"        <summary>\n"
            f'          <span class="card-head">{badge(key)} <span class="card-title">{esc(title)}</span></span>'
            f"{abstract_block}\n"
            f"        </summary>\n"
            f'        <div class="domain-body">\n'
            f"{tag_block}"
            f"{body_html}\n"
            f'          <p class="domain-source"><a href="{esc(link)}" target="_blank" rel="noopener">GitHub で raw .md を見る&nbsp;↗</a></p>\n'
            f"        </div>\n"
            f"      </details>"
        )
    if not cards:
        return ""
    return (
        '    <section class="section" id="domains">\n'
        '      <h2 class="section-title">今日のテーマ概要'
        '        <span class="section-controls">'
        '<button type="button" id="expand-all">すべて展開</button>'
        '<button type="button" id="collapse-all">すべて閉じる</button></span>'
        "</h2>\n"
        '      <p class="section-note">各カードをクリックすると、そのドメインの全文が開きます。</p>\n'
        + "\n".join(cards)
        + "\n    </section>\n"
    )


def render_box_section(title: str, body: str, box_class: str, anchor: str) -> str:
    subs = split_subsections(strip_trailing_meta(body))
    parts = []
    for head, sub_body in subs:
        if not head:  # 前文
            parts.append(f'      <div class="section-intro">{md_html(sub_body)}</div>')
            continue
        parts.append(
            f'      <div class="{box_class}">\n'
            f"        <h3>{esc(head)}</h3>\n"
            f"        {md_html(sub_body)}\n"
            f"      </div>"
        )
    if not parts:  # サブ見出しが無ければ素直に本文を出す
        parts.append(f"      {md_html(strip_trailing_meta(body))}")
    return (
        f'    <section class="section" id="{anchor}">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        + "\n".join(parts)
        + "\n    </section>\n"
    )


def render_actions_section(title: str, body: str) -> str:
    subs = split_subsections(strip_trailing_meta(body))
    parts = []
    for head, sub_body in subs:
        key = normalize_domain_key(head) if head else None
        if key:
            css = DOMAIN_CSS[key]
            label = f"{badge(key)} {esc(DOMAIN_JP[key])}"
            parts.append(
                f'      <details class="card card-{css}">\n'
                f"        <summary>{label}</summary>\n"
                f'        <div class="detail-content">{md_html(sub_body)}</div>\n'
                f"      </details>"
            )
        elif head:
            parts.append(
                f'      <div class="insight"><h3>{esc(head)}</h3>{md_html(sub_body)}</div>'
            )
        else:
            parts.append(f'      <div class="section-intro">{md_html(sub_body)}</div>')
    if not parts:
        parts.append(f"      {md_html(strip_trailing_meta(body))}")
    return (
        '    <section class="section" id="next-actions">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        + "\n".join(parts)
        + "\n    </section>\n"
    )


def render_generic_section(title: str, body: str, anchor: str) -> str:
    return (
        f'    <section class="section" id="{anchor}">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        f"      {md_html(strip_trailing_meta(body))}\n"
        f"    </section>\n"
    )


# --- ナビ / ページ骨格 -------------------------------------------------------
def nav_html(date: str, report_dates: List[str]) -> str:
    idx = report_dates.index(date) if date in report_dates else -1
    prev_d = report_dates[idx - 1] if idx > 0 else None
    next_d = report_dates[idx + 1] if 0 <= idx < len(report_dates) - 1 else None
    left = f'<a href="{prev_d}.html" class="nav-prev">{prev_d}</a>' if prev_d else "<span></span>"
    right = f'<a href="{next_d}.html" class="nav-next">{next_d}</a>' if next_d else "<span></span>"
    return (
        '    <nav class="nav">\n'
        f"      {left}\n"
        '      <a href="../index.html">一覧</a>\n'
        f"      {right}\n"
        "    </nav>\n"
    )


def inline_css() -> str:
    if STYLE_CSS.is_file():
        return STYLE_CSS.read_text(encoding="utf-8")
    return ""


PAGE_SCRIPT = """
(function () {
  function openHash() {
    var h = (location.hash || '').replace('#', '');
    if (!h) return;
    var el = document.getElementById(h);
    if (el && el.tagName === 'DETAILS') {
      el.open = true;
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
  window.addEventListener('hashchange', openHash);
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('a[href^="#card-"]').forEach(function (a) {
      a.addEventListener('click', function () {
        var el = document.getElementById(a.getAttribute('href').slice(1));
        if (el && el.tagName === 'DETAILS') el.open = true;
      });
    });
    var ex = document.getElementById('expand-all'), co = document.getElementById('collapse-all');
    if (ex) ex.addEventListener('click', function () {
      document.querySelectorAll('details.domain-details').forEach(function (d) { d.open = true; });
    });
    if (co) co.addEventListener('click', function () {
      document.querySelectorAll('details.domain-details').forEach(function (d) { d.open = false; });
    });
    openHash();
  });
})();
""".strip()


def build_report_html(date: str, report_dates: List[str]) -> Optional[str]:
    integ = find_integration(date)
    if integ is None:
        print(f"  ! {date}: 統合レポート (_integrations/{date}_*.md) が無いためスキップ", file=sys.stderr)
        return None
    h1, sections, _ = split_h1_sections(integ.read_text(encoding="utf-8"))
    page_title = h1 or f"デイリーレポート {date}"

    # トピック表からドメイン→GitHubリンクの対応を作る
    topic_rows: List[Tuple[str, str, str]] = []
    topic_links: Dict[str, str] = {}
    for head, body in sections:
        if "トピック" in head:
            topic_rows = parse_topic_table(body)
            for key, _theme, link in topic_rows:
                if key in DOMAIN_KEYS and link:
                    topic_links[key] = link
            break

    def is_overview_head(h: str) -> bool:
        return "テーマ概要" in h or ("概要" in h and "蓄積" not in h and "スナップショット" not in h)

    # テーマ概要
    theme_overview: Dict[str, str] = {}
    for head, body in sections:
        if is_overview_head(head):
            parsed = parse_theme_overview(body)
            if parsed:
                theme_overview = parsed
                break

    body_parts: List[str] = []
    used_anchors = {"topics", "domains", "next-actions"}

    def uniq(anchor: str) -> str:
        a, k = anchor, 2
        while a in used_anchors:
            a, k = f"{anchor}-{k}", k + 1
        used_anchors.add(a)
        return a

    used_topic = used_overview = False
    for idx, (head, body) in enumerate(sections):
        if "トピック" in head and not used_topic:
            body_parts.append(render_topic_table(topic_rows) or render_generic_section(head, body, uniq("topics-fb")))
            used_topic = True
        elif is_overview_head(head) and not used_overview:
            cards = render_domain_cards(theme_overview, topic_links, date)
            body_parts.append(cards or render_generic_section(head, body, uniq("domains-fb")))
            used_overview = True
        elif "蓄積" in head or "スナップショット" in head:
            body_parts.append(render_generic_section(head, body, uniq("accumulation")))
        elif "横断" in head:
            body_parts.append(render_box_section(head, body, "insight", uniq("patterns")))
        elif "接続" in head:
            body_parts.append(render_box_section(head, body, "connection", uniq("connections")))
        elif "洞察" in head:
            body_parts.append(render_box_section(head, body, "insight", uniq("insights")))
        elif "アクション" in head or "指令" in head:
            body_parts.append(render_actions_section(head, body))
        else:
            slug = re.sub(r"[^a-z0-9]+", "-", head.lower()).strip("-")
            body_parts.append(render_generic_section(head, body, uniq(f"sec-{idx}-{slug}" if slug else f"sec-{idx}")))

    # テーマ概要セクションが統合レポートに無くてもカードは出す
    if not used_overview:
        cards = render_domain_cards(theme_overview, topic_links, date)
        if cards:
            # トピック表の直後に挿入
            insert_at = 1 if used_topic and body_parts else 0
            body_parts.insert(insert_at, cards)

    css = inline_css()
    html_doc = f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{esc(page_title)}</title>
  <style>
{css}
  </style>
</head>
<body>
  <div class="container">
{nav_html(date, report_dates)}    <header class="report-header">
      <h1>デイリーレポート</h1>
      <div class="report-date">{esc(date)}</div>
    </header>
{''.join(body_parts)}    <footer class="footer">
      <p><em>{esc(GENERATED_BY)}</em></p>
    </footer>
  </div>
  <script>
{PAGE_SCRIPT}
  </script>
</body>
</html>
"""
    return html_doc


# --- index.html --------------------------------------------------------------
def topics_summary_for(date: str) -> str:
    """index 用：その日のトピック（テーマ名）をカンマ区切りで。"""
    integ = find_integration(date)
    themes: List[str] = []
    if integ is not None:
        _h1, sections, _ = split_h1_sections(integ.read_text(encoding="utf-8"))
        for head, body in sections:
            if "トピック" in head:
                for _key, theme, _link in parse_topic_table(body):
                    if theme:
                        themes.append(theme)
                break
    if not themes:
        for key in DOMAIN_KEYS:
            e = find_domain_entry(key, date)
            if e:
                t, _tags, _b = parse_domain_entry(e)
                themes.append(t)
    return "、".join(themes)


def build_index_html(report_dates: List[str]) -> str:
    css = inline_css()
    items = []
    for d in sorted(report_dates, reverse=True):
        topics = esc(topics_summary_for(d))
        items.append(
            f'      <li><a href="reports/{d}.html">\n'
            f'        <span class="report-list-date">{d}</span>\n'
            f'        <span class="report-list-topics">{topics}</span>\n'
            f"      </a></li>"
        )
    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>知識統合システム — デイリーレポート</title>
  <style>
{css}
  </style>
</head>
<body>
  <div class="container">
    <div class="index-header">
      <h1>知識統合システム</h1>
      <p>多重影分身・日次学習レポート</p>
    </div>
    <ul class="report-list">
{chr(10).join(items)}
    </ul>
    <div class="footer">
      <p><em>{esc(GENERATED_BY)}</em></p>
    </div>
  </div>
</body>
</html>
"""


# --- メイン ------------------------------------------------------------------
def today_str() -> str:
    try:
        out = subprocess.run(["date", "+%Y-%m-%d"], capture_output=True, text=True, check=True)
        s = out.stdout.strip()
        if DATE_RE.fullmatch(s):
            return s
    except Exception:
        pass
    return _dt.date.today().isoformat()


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: List[str]) -> int:
    args = [a for a in argv[1:] if a]
    backfill_all = "--all" in args
    date_args = [a for a in args if not a.startswith("-")]

    if backfill_all:
        target_dates = all_integration_dates()
        if not target_dates:
            sys.exit("エラー: _integrations/ にレポートが見つかりません。")
    else:
        date = date_args[0] if date_args else today_str()
        if not DATE_RE.fullmatch(date):
            sys.exit(f"エラー: 日付は YYYY-MM-DD 形式で指定してください（受け取った値: {date!r}）。")
        target_dates = [date]

    # 生成対象 = 指定日 ∪ 既に docs/reports/ にある日（ナビ整合のため再生成）
    report_dates = sorted(set(existing_report_dates()) | set(target_dates))

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    written = []
    final_dates = []
    for d in report_dates:
        doc = build_report_html(d, report_dates)
        if doc is None:
            # 統合レポートが無い → 既存 .html があればそのまま残す
            if (REPORTS_DIR / f"{d}.html").is_file():
                final_dates.append(d)
            continue
        if write_if_changed(REPORTS_DIR / f"{d}.html", doc):
            written.append(f"docs/reports/{d}.html")
        final_dates.append(d)

    # ナビが report_dates 前提で生成されているので、欠けがあった場合に備えてもう一周（軽量）
    if set(final_dates) != set(report_dates):
        for d in final_dates:
            doc = build_report_html(d, final_dates)
            if doc and write_if_changed(REPORTS_DIR / f"{d}.html", doc):
                if f"docs/reports/{d}.html" not in written:
                    written.append(f"docs/reports/{d}.html")

    if write_if_changed(DOCS_DIR / "index.html", build_index_html(final_dates)):
        written.append("docs/index.html")

    if written:
        print("生成/更新:")
        for w in written:
            print(f"  - {w}")
    else:
        print("変更なし（生成済みと同一）。")
    print(f"レポート総数: {len(final_dates)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
