#!/usr/bin/env python3
"""
build_report_html.py — 日次学習レポートを「自己完結 HTML」に変換する。

使い方:
    python3 scripts/build_report_html.py [YYYY-MM-DD]   # 指定日（省略時はローカル今日）
    python3 scripts/build_report_html.py --all          # 既存の全レポートを再生成（バックフィル）

挙動:
- `_integrations/<date>_*.md`（統合レポート）と `domains/<分野>/<date>_*.md`（各ドメイン全文）
  を読み込み、`docs/reports/<date>.html` を生成する。
- 各ドメインの「今日のテーマ概要」カード自体が <details>（折りたたみ）で、クリックすると
  そのドメインの全文 markdown がレンダリングされて開く。ローカルの .md は一切変更しない。
- CSS は `docs/style.css` をインライン展開するので、生成 HTML は単体でも開ける／共有できる。
- `docs/index.html` を再生成し、`docs/reports/` に既に存在するレポートのナビ（前日/翌日）も
  整合するよう貼り直す（過去 .md の一括 HTML 化はしない＝既存 .html があるものだけ）。

依存: 標準ライブラリ + `markdown`（`pip install markdown` / 既存環境では導入済み）。
"""
from __future__ import annotations

import datetime as _dt
import html
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import markdown as _markdown
except ImportError:  # pragma: no cover
    sys.exit("エラー: Python の markdown ライブラリが必要です（pip install markdown）。")

# --- パス定義 ----------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
INTEGRATIONS_DIR = ROOT / "_integrations"
DOMAINS_DIR = ROOT / "domains"
DOCS_DIR = ROOT / "docs"
REPORTS_DIR = DOCS_DIR / "reports"
STYLE_CSS = DOCS_DIR / "style.css"

GITHUB_BLOB = "https://github.com/YamamotoNaoyuki/DailyLearning/blob/main"
GENERATED_BY = "Generated by 知識統合システム"

# レポート／一覧の先頭に毎回テンプレ的に並べる外部リンク。(表示名, URL) のタプル。
# 「このレポートを見れば欲しい情報に全部アクセスできる」ことを目指すための起点リンク集。
# ここに追記すれば全レポートに反映される。
TOP_LINKS: List[Tuple[str, str]] = [
    ("ニュース", "https://news.nullevi.app/"),
]

# (フォルダ名, バッジ表示名, CSS サフィックス, アクション節用の日本語名)
# 過去ドメイン（tech / cs / bread / philosophy / sdv）は domains/_archive/ に退避済みのため、現役ローテーション対象外。
# 過去レポートで使われていた CSS サフィックスは docs/style.css に残してある（既存 HTML の表示を壊さないため）。
DOMAINS: List[Tuple[str, str, str, str]] = [
    ("music", "music", "music", "音楽"),
    ("piano", "piano", "piano", "ピアノ"),
    ("golf", "golf", "golf", "ゴルフ"),
    ("anatomy", "anatomy", "anatomy", "解剖学"),
    ("house-hunting", "house", "house-hunting", "家探し"),
    ("deutsch", "deutsch", "deutsch", "ドイツ語"),
    ("other", "other", "other", "その他"),
]
DOMAIN_KEYS = [d[0] for d in DOMAINS]
DOMAIN_LABEL = {d[0]: d[1] for d in DOMAINS}
DOMAIN_CSS = {d[0]: d[2] for d in DOMAINS}
DOMAIN_JP = {d[0]: d[3] for d in DOMAINS}

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")
MD_EXTENSIONS = ["tables", "fenced_code", "attr_list", "nl2br"]

_LIST_ITEM_RE = re.compile(r"^ {0,3}(?:[-*+]|\d+[.)])\s+\S")
_FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})")


def loosen_lists(text: str) -> str:
    """箇条書きの直前に空行を補う。

    `/learn` の出力は `説明文:` の直後に空行なしで `- 項目` を続けることが多く、
    Python-Markdown はそれをリストと認識しない（段落の続きの平文になる）。
    フェンスコードブロックの中は対象外。
    """
    out: List[str] = []
    in_fence = False
    fence_char = ""
    for ln in text.split("\n"):
        mf = _FENCE_RE.match(ln)
        if mf:
            if not in_fence:
                in_fence, fence_char = True, mf.group(1)[0]
            elif ln.strip().startswith(fence_char * 3):
                in_fence = False
            out.append(ln)
            continue
        if (not in_fence) and out and _LIST_ITEM_RE.match(ln):
            prev = out[-1]
            if prev.strip() and not _LIST_ITEM_RE.match(prev) and not prev.startswith((" ", "\t")):
                out.append("")
        out.append(ln)
    return "\n".join(out)


# --- markdown レンダリング ---------------------------------------------------
def md_html(text: str) -> str:
    """ブロックレベルの markdown → HTML。"""
    return _markdown.markdown(loosen_lists(text or ""), extensions=MD_EXTENSIONS, output_format="html")


def md_inline(text: str) -> str:
    """1 行ぶんの markdown をインライン HTML に（外側の <p> を剥がす）。"""
    out = md_html(text).strip()
    m = re.match(r"^<p>(.*)</p>$", out, re.S)
    return (m.group(1) if m else out).strip()


def esc(text: str) -> str:
    return html.escape(text, quote=True)


# --- ファイル探索 ------------------------------------------------------------
def normalize_domain_key(raw: str) -> Optional[str]:
    key = raw.strip().lower()
    if key in DOMAIN_KEYS:
        return key
    for k in DOMAIN_KEYS:
        if k == key or k.startswith(key) or key.startswith(k):
            return k
        if DOMAIN_LABEL[k] == key or DOMAIN_JP[k] == raw.strip():
            return k
    return None


def find_domain_entry(domain: str, date: str) -> Optional[Path]:
    d = DOMAINS_DIR / domain
    if not d.is_dir():
        return None
    cands = sorted(p for p in d.glob(f"{date}_*.md") if p.name != "_summary.md")
    return cands[0] if cands else None


def find_integration(date: str) -> Optional[Path]:
    if not INTEGRATIONS_DIR.is_dir():
        return None
    cands = sorted(INTEGRATIONS_DIR.glob(f"{date}_*.md"))
    # 数字サフィックス（_2 等）が付かないものを優先
    cands.sort(key=lambda p: (re.search(r"_\d+\.md$", p.name) is not None, p.name))
    return cands[0] if cands else None


def existing_report_dates() -> List[str]:
    if not REPORTS_DIR.is_dir():
        return []
    out = []
    for p in REPORTS_DIR.glob("*.html"):
        m = DATE_RE.match(p.stem)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


def all_integration_dates() -> List[str]:
    if not INTEGRATIONS_DIR.is_dir():
        return []
    out = []
    for p in INTEGRATIONS_DIR.glob("*.md"):
        m = DATE_RE.match(p.name)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


# --- 統合レポートのパース ----------------------------------------------------
def split_h1_sections(md_text: str) -> Tuple[str, List[Tuple[str, str]], str]:
    """`# H1` と `## セクション` で分割。戻り値 (h1, [(heading, body)], footer_text)。"""
    lines = md_text.splitlines()
    h1 = ""
    # 先頭の H1 を取り出す
    for idx, ln in enumerate(lines):
        if ln.startswith("# "):
            h1 = ln[2:].strip()
            lines = lines[idx + 1:]
            break
    sections: List[Tuple[str, str]] = []
    head: Optional[str] = None
    buf: List[str] = []
    for ln in lines:
        if ln.startswith("## "):
            if head is not None:
                sections.append((head, "\n".join(buf).strip()))
            head = ln[3:].strip()
            buf = []
        else:
            buf.append(ln)
    if head is not None:
        sections.append((head, "\n".join(buf).strip()))
    # フッター（最後のセクション本文末尾の "*Generated by ...*" や "---"）はそのまま本文に残し、
    # 出力時に固定フッターを別途付ける。ここでは footer は空文字を返す。
    return h1, sections, ""


def split_subsections(body: str) -> List[Tuple[str, str]]:
    """`### サブ見出し` で分割。先頭の前文は ("", text)。空のエントリは除く。"""
    out: List[Tuple[str, str]] = []
    head = ""
    buf: List[str] = []
    for ln in body.splitlines():
        if ln.startswith("### "):
            if head or "".join(buf).strip():
                out.append((head, "\n".join(buf).strip()))
            head = ln[4:].strip()
            buf = []
        else:
            buf.append(ln)
    if head or "".join(buf).strip():
        out.append((head, "\n".join(buf).strip()))
    return [(h, b) for (h, b) in out if h or b]


def strip_trailing_meta(body: str) -> str:
    """セクション本文末尾の "---" / "*Generated by ...*" を取り除く。"""
    lines = body.splitlines()
    while lines:
        s = lines[-1].strip()
        if s == "" or s == "---" or re.match(r"^\*.*知識統合システム.*\*$", s) or re.match(r"^_.*知識統合システム.*_$", s):
            lines.pop()
        else:
            break
    return "\n".join(lines).strip()


def parse_theme_overview(body: str) -> Dict[str, str]:
    """`- **domain**: text` の箇条書きを {domain_key: abstract_html} に。"""
    result: Dict[str, str] = {}
    for ln in body.splitlines():
        m = re.match(r"^\s*[-*]\s+\*\*([^*]+)\*\*\s*[:：]\s*(.+?)\s*$", ln)
        if not m:
            continue
        key = normalize_domain_key(m.group(1))
        if key:
            result[key] = md_inline(m.group(2))
    return result


def parse_topic_table(body: str) -> List[Tuple[str, str, str]]:
    """markdown テーブル → [(domain_key_or_raw, theme_text, github_link)]。"""
    rows: List[Tuple[str, str, str]] = []
    for ln in body.splitlines():
        ln = ln.strip()
        if not ln.startswith("|"):
            continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) < 2:
            continue
        joined = "".join(cells)
        if joined and set(joined) <= set("-:| "):  # 区切り行
            continue
        if cells[0] in ("分野", "domain", "Domain", "Field"):  # ヘッダ行
            continue
        domain_raw = cells[0]
        theme = cells[1]
        link = ""
        for cell in cells[2:]:
            m = re.search(r"\((https?://[^)]+)\)", cell)
            if m:
                link = m.group(1)
                break
        if not link:
            m = re.search(r"\[([^\]]+)\]\((https?://[^)]+)\)", theme)
            if m:
                theme = m.group(1).strip()
                link = m.group(2)
        # テーマ列に残った markdown リンク記法を平文化
        theme = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", theme).strip()
        key = normalize_domain_key(domain_raw) or domain_raw.lower()
        rows.append((key, theme, link))
    return rows


# --- ドメインエントリのパース ------------------------------------------------
def parse_domain_entry(path: Path) -> Tuple[str, List[str], str]:
    """ドメイン .md → (title, tags, body_html)。先頭の H1 とメタ行（日付/分野/タグ）を除く。"""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    title = path.stem
    tags: List[str] = []
    i = 0
    n = len(lines)
    # H1
    while i < n and lines[i].strip() == "":
        i += 1
    if i < n and lines[i].lstrip().startswith("# "):
        title = lines[i].lstrip()[2:].strip()
        i += 1
    # メタ行（**日付**:, **分野**:, **タグ**:）と空行をスキップ
    while i < n:
        s = lines[i].strip()
        if s == "":
            i += 1
            continue
        mm = re.match(r"^\*\*\s*(日付|分野|タグ|tags?|date|domain)\s*\*\*\s*[:：]", s)
        if mm:
            if "タグ" in s or s.lower().startswith("**tag"):
                tags = re.findall(r"#\S+", s)
            i += 1
            continue
        break
    body_md = "\n".join(lines[i:]).strip()
    return title, tags, md_html(body_md)


# --- HTML 部品 ---------------------------------------------------------------
def badge(domain_key: str) -> str:
    css = DOMAIN_CSS.get(domain_key, domain_key)
    label = DOMAIN_LABEL.get(domain_key, domain_key)
    return f'<span class="badge badge-{css}">{esc(label)}</span>'


def github_link_for_entry(entry: Path) -> str:
    rel = entry.relative_to(ROOT).as_posix()
    return f"{GITHUB_BLOB}/{rel}"


def render_topic_table(rows: List[Tuple[str, str, str]]) -> str:
    if not rows:
        return ""
    body_rows = []
    for key, theme, link in rows:
        in_page = key in DOMAIN_KEYS
        theme_cell = (
            f'<a href="#card-{key}">{esc(theme)}</a>' if in_page else esc(theme)
        )
        src_cell = (
            f'<a href="{esc(link)}" class="ext-link" target="_blank" rel="noopener">md&nbsp;↗</a>'
            if link else ""
        )
        b = badge(key) if in_page else f'<span class="badge badge-other">{esc(key)}</span>'
        body_rows.append(
            f"          <tr><td>{b}</td><td>{theme_cell}</td><td class=\"src-col\">{src_cell}</td></tr>"
        )
    return (
        '    <section class="section" id="topics">\n'
        '      <h2 class="section-title">今日のトピック一覧</h2>\n'
        '      <table class="topic-table">\n'
        "        <thead><tr><th>分野</th><th>テーマ</th><th></th></tr></thead>\n"
        "        <tbody>\n" + "\n".join(body_rows) + "\n        </tbody>\n"
        "      </table>\n"
        "    </section>\n"
    )


def render_domain_cards(theme_overview: Dict[str, str], topic_links: Dict[str, str], date: str) -> str:
    cards = []
    for key in DOMAIN_KEYS:
        entry = find_domain_entry(key, date)
        if entry is None:
            continue
        title, tags, body_html = parse_domain_entry(entry)
        link = topic_links.get(key) or github_link_for_entry(entry)
        css = DOMAIN_CSS[key]
        abstract = theme_overview.get(key, "")
        abstract_block = (
            f'\n          <span class="card-abstract">{abstract}</span>' if abstract else ""
        )
        tag_block = ""
        if tags:
            tag_block = (
                '          <div class="domain-tags">'
                + " ".join(f'<span class="tag">{esc(t)}</span>' for t in tags)
                + "</div>\n"
            )
        cards.append(
            f'      <details id="card-{key}" class="card card-{css} domain-details">\n'
            f"        <summary>\n"
            f'          <span class="card-head">{badge(key)} <span class="card-title">{esc(title)}</span></span>'
            f"{abstract_block}\n"
            f"        </summary>\n"
            f'        <div class="domain-body">\n'
            f"{tag_block}"
            f"{body_html}\n"
            f'          <p class="domain-source"><a href="{esc(link)}" target="_blank" rel="noopener">GitHub で raw .md を見る&nbsp;↗</a></p>\n'
            f'          <button type="button" class="collapse-card">▲ 閉じる</button>\n'
            f"        </div>\n"
            f"      </details>"
        )
    if not cards:
        return ""
    return (
        '    <section class="section" id="domains">\n'
        '      <h2 class="section-title">今日のテーマ概要'
        '        <span class="section-controls">'
        '<button type="button" id="expand-all">すべて展開</button>'
        '<button type="button" id="collapse-all">すべて閉じる</button></span>'
        "</h2>\n"
        '      <p class="section-note">各カードをクリックすると、そのドメインの全文が開きます。</p>\n'
        + "\n".join(cards)
        + "\n    </section>\n"
    )


def render_box_section(title: str, body: str, box_class: str, anchor: str) -> str:
    subs = split_subsections(strip_trailing_meta(body))
    parts = []
    for head, sub_body in subs:
        if not head:  # 前文
            parts.append(f'      <div class="section-intro">{md_html(sub_body)}</div>')
            continue
        parts.append(
            f'      <div class="{box_class}">\n'
            f"        <h3>{esc(head)}</h3>\n"
            f"        {md_html(sub_body)}\n"
            f"      </div>"
        )
    if not parts:  # サブ見出しが無ければ素直に本文を出す
        parts.append(f"      {md_html(strip_trailing_meta(body))}")
    return (
        f'    <section class="section" id="{anchor}">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        + "\n".join(parts)
        + "\n    </section>\n"
    )


def render_actions_section(title: str, body: str) -> str:
    subs = split_subsections(strip_trailing_meta(body))
    parts = []
    for head, sub_body in subs:
        key = normalize_domain_key(head) if head else None
        if key:
            css = DOMAIN_CSS[key]
            label = f"{badge(key)} {esc(DOMAIN_JP[key])}"
            parts.append(
                f'      <details class="card card-{css}">\n'
                f"        <summary>{label}</summary>\n"
                f'        <div class="detail-content">{md_html(sub_body)}</div>\n'
                f"      </details>"
            )
        elif head:
            parts.append(
                f'      <div class="insight"><h3>{esc(head)}</h3>{md_html(sub_body)}</div>'
            )
        else:
            parts.append(f'      <div class="section-intro">{md_html(sub_body)}</div>')
    if not parts:
        parts.append(f"      {md_html(strip_trailing_meta(body))}")
    return (
        '    <section class="section" id="next-actions">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        + "\n".join(parts)
        + "\n    </section>\n"
    )


def render_generic_section(title: str, body: str, anchor: str) -> str:
    return (
        f'    <section class="section" id="{anchor}">\n'
        f'      <h2 class="section-title">{esc(title)}</h2>\n'
        f"      {md_html(strip_trailing_meta(body))}\n"
        f"    </section>\n"
    )


# --- 「今日のX」セクション（data/x/<date>.json を X 風に埋め込む） -----------
X_DATA_DIR = ROOT / "data" / "x"
_X_MAX_PER_ACCOUNT = 100          # レポートが肥大化しないよう、1アカウントあたりの表示上限
_X_MENTION_RE = re.compile(r"(?<![\w@/])@(\w{1,20})")
_X_HASHTAG_RE = re.compile(r"(?<![\w&#＃])[#＃](\w+)")
_X_TCO_RE = re.compile(r"https?://t\.co/\w+")

# X 風アイコン: <symbol> を一度だけ定義し、各所で <use> で参照（HTML サイズ削減）
_X_ICON_PATHS = {
    "reply": ('M1.751 10c0-4.42 3.584-8 8.005-8h4.366c4.49 0 8.129 3.64 8.129 8.13 0 2.96-1.607 5.68-4.196 '
              '7.11l-8.054 4.46v-3.69h-.067c-4.49.1-8.183-3.51-8.183-8.01zm8.005-6c-3.317 0-6.005 2.69-6.005 6 0 3.37 '
              '2.77 6.08 6.138 6.01l.351-.01h1.761v2.3l5.087-2.81c1.951-1.08 3.163-3.13 3.163-5.36 0-3.39-2.744-6.13-6.129-6.13H9.756z'),
    "rt": ('M4.5 3.88l4.432 4.14-1.364 1.46L5.5 7.55V16c0 1.1.896 2 2 2H13v2H7.5c-2.209 0-4-1.79-4-4V7.55L1.432 '
           '9.48.068 8.02 4.5 3.88zM16.5 6H11V4h5.5c2.209 0 4 1.79 4 4v8.45l2.068-1.93 1.364 1.46-4.432 4.14-4.432-4.14 '
           '1.364-1.46 2.068 1.93V8c0-1.1-.896-2-2-2z'),
    "like": ('M16.697 5.5c-1.222-.06-2.679.51-3.89 2.16l-.805 1.09-.806-1.09C9.984 6.01 8.526 5.44 7.304 5.5c-1.243.07-2.349.78-2.91 '
             '1.91-.552 1.12-.633 2.78.479 4.82 1.074 1.97 3.257 4.27 7.129 6.61 3.87-2.34 6.052-4.64 7.126-6.61 1.111-2.04 '
             '1.03-3.7.477-4.82-.561-1.13-1.666-1.84-2.908-1.91zm4.187 7.69c-1.351 2.48-4.001 5.12-8.379 7.67l-.503.3-.504-.3c-4.379-2.55-7.029-5.19-8.382-7.67-1.36-2.5-1.41-4.86-.514-6.67.887-1.79 '
             '2.647-2.91 4.601-3.01 1.651-.09 3.368.56 4.798 2.01 1.429-1.45 3.146-2.1 4.796-2.01 1.954.1 3.714 1.22 4.601 3.01.896 1.81.846 4.17-.514 6.67z'),
    "link": ('M11.96 14.945c-.067 0-.136-.01-.203-.027-1.13-.318-2.097-.986-2.795-1.932-.832-1.125-1.176-2.508-.968-3.893s.945-2.605 '
             '2.07-3.438l3.79-2.81c2.31-1.71 5.575-1.225 7.29 1.084 1.71 2.31 1.225 5.576-1.084 7.286l-1.51 1.121c-.443.328-1.068.236-1.396-.207-.33-.443-.237-1.068.206-1.397l1.51-1.12c1.43-1.06 '
             '1.732-3.09.672-4.518-1.06-1.43-3.09-1.732-4.52-.672l-3.79 2.81c-.692.513-1.143 1.265-1.27 2.118s.083 1.704.59 2.396c.43.583 1.034 1 1.726 1.193.53.15.84.7.69 1.23-.123.443-.527.737-.96.737zm-2.21 '
             '5.451l3.79-2.81c1.42-1.05 1.72-3.061.67-4.491-1.05-1.43-3.061-1.722-4.491-.672l-1.51 1.12c-.443.327-1.068.236-1.396-.207-.33-.443-.237-1.068.206-1.397l1.51-1.12c2.31-1.71 '
             '5.576-1.225 7.286 1.084 1.71 2.31 1.225 5.576-1.084 7.286l-3.79 2.81c-.831.616-1.81.911-2.78.911-1.6 0-3.172-.736-4.181-2.103-.832-1.125-1.176-2.509-.968-3.894s.945-2.605 '
             '2.07-3.438l1.51-1.12c.443-.328 1.068-.237 1.396.206.33.443.237 1.068-.206 1.397l-1.51 1.12c-1.43 1.06-1.731 3.091-.671 4.521 1.06 1.43 3.09 1.72 4.52.67z'),
    "verified": ('M20.396 11c-.018-.646-.215-1.275-.57-1.816-.354-.54-.852-.972-1.438-1.246.223-.607.27-1.264.14-1.897-.131-.634-.437-1.218-.882-1.687-.47-.445-1.053-.75-1.687-.882-.633-.13-1.29-.083-1.897.14-.273-.587-.704-1.086-1.245-1.443C11.276 '
                 '1.413 10.647 1.215 10 1.196c-.646.018-1.275.215-1.816.57-.54.354-.972.852-1.246 1.438-.607-.223-1.264-.27-1.897-.14-.634.131-1.218.437-1.687.882-.445.47-.75 1.053-.882 1.687-.13.633-.083 1.29.14 '
                 '1.897-.587.273-1.086.704-1.443 1.245C.413 10.724.215 11.353.196 12c.018.646.215 1.275.57 1.816.354.54.852.972 1.438 1.246-.223.607-.27 1.264-.14 1.897.131.634.437 1.218.882 1.687.47.445 1.053.75 1.687.882.633.13 '
                 '1.29.083 1.897-.14.273.587.704 1.086 1.245 1.443.541.357 1.17.555 1.816.574.646-.018 1.275-.215 1.816-.57.54-.354.972-.852 1.246-1.438.607.223 1.264.27 1.897.14.634-.131 1.218-.437 1.687-.882.445-.47.75-1.053.882-1.687.13-.633.083-1.29-.14-1.897.587-.273 '
                 '1.086-.704 1.443-1.245.357-.541.555-1.17.574-1.816zM9.662 14.85l-3.429-3.428 1.293-1.302 2.072 2.072 4.4-4.794 1.347 1.246z'),
}
_X_ICON_VIEWBOX = {"reply": "0 0 24 24", "rt": "0 0 24 24", "like": "0 0 24 24", "link": "0 0 24 24", "verified": "0 0 22 22"}
X_ICON_DEFS = (
    '<svg style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true">'
    + "".join(f'<symbol id="x-i-{k}" viewBox="{_X_ICON_VIEWBOX[k]}"><path d="{v}"></path></symbol>'
             for k, v in _X_ICON_PATHS.items())
    + "</svg>"
)
_X_ICO_REPLY = '<svg class="x-ico" aria-hidden="true"><use href="#x-i-reply"></use></svg>'
_X_ICO_RT = '<svg class="x-ico" aria-hidden="true"><use href="#x-i-rt"></use></svg>'
_X_ICO_LIKE = '<svg class="x-ico" aria-hidden="true"><use href="#x-i-like"></use></svg>'
_X_ICO_LINK = '<svg class="x-ico" aria-hidden="true"><use href="#x-i-link"></use></svg>'
_X_ICO_VERIFIED = '<svg class="x-verified" aria-hidden="true"><use href="#x-i-verified"></use></svg>'


def load_x_data(date: str) -> Optional[Dict[str, Any]]:
    p = X_DATA_DIR / f"{date}.json"
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _parse_x_time(s: str) -> Optional[_dt.datetime]:
    if not s:
        return None
    s = s.strip()
    try:
        d = _dt.datetime.fromisoformat(s.replace("Z", "+00:00"))
        return d if d.tzinfo else d.replace(tzinfo=_dt.timezone.utc)
    except ValueError:
        pass
    for fmt in ("%a %b %d %H:%M:%S %z %Y", "%Y-%m-%d %H:%M:%S %z", "%Y-%m-%dT%H:%M:%S%z"):
        try:
            return _dt.datetime.strptime(s, fmt)
        except ValueError:
            continue
    return None


def _rel_time(created_at: str, ref: Optional[_dt.datetime]) -> Tuple[str, str]:
    """X 風の相対時刻 (表示文字列, ツールチップ用の絶対時刻) を返す。"""
    d = _parse_x_time(created_at)
    if d is None:
        return (created_at or ""), ""
    local = d.astimezone()
    abs_str = local.strftime("%Y-%m-%d %H:%M")
    base = ref or _dt.datetime.now(_dt.timezone.utc)
    delta = max(0.0, (base - d).total_seconds())
    if delta < 60:
        rel = "今"
    elif delta < 3600:
        rel = f"{int(delta // 60)}分"
    elif delta < 86400:
        rel = f"{int(delta // 3600)}時間"
    elif delta < 86400 * 7:
        rel = f"{int(delta // 86400)}日"
    elif local.year == base.astimezone().year:
        rel = f"{local.month}月{local.day}日"
    else:
        rel = f"{local.year}年{local.month}月{local.day}日"
    return rel, abs_str


def _fmt_count(n: Any) -> str:
    try:
        n = int(n or 0)
    except (TypeError, ValueError):
        return ""
    if n <= 0:
        return ""
    if n < 10000:
        return f"{n:,}"
    if n < 10 ** 8:
        return f"{n / 10000:.1f}".rstrip("0").rstrip(".") + "万"
    return f"{n / 10 ** 8:.1f}".rstrip("0").rstrip(".") + "億"


_X_TWEET_PERMALINK_RE = re.compile(r"https?://(?:www\.)?(?:x|twitter)\.com/\w+/status/\d+", re.I)
_X_TRAILING_TCO_RE = re.compile(r"\s*https?://t\.co/\w+\s*$")


def _clean_tweet_text(text: str, urls: Any, has_card: bool) -> str:
    """X 同様、メディア／引用ツイートを指す末尾の t.co を本文から取り除く。"""
    s = (text or "").rstrip()
    if not has_card:
        return s
    umap = {u.get("tco"): (u.get("expanded") or "") for u in (urls or []) if isinstance(u, dict) and u.get("tco")}
    while True:
        m = _X_TRAILING_TCO_RE.search(s)
        if not m:
            break
        tco = m.group(0).strip()
        exp = umap.get(tco)
        if tco in umap and exp and not _X_TWEET_PERMALINK_RE.match(exp):
            break  # 通常の外部リンク → 残す
        s = s[: m.start()].rstrip()
    return s


def linkify_tweet_text(text: str, urls: Optional[List[Dict[str, str]]]) -> str:
    s = esc(text or "")
    s = _X_HASHTAG_RE.sub(
        lambda m: f'<a href="https://x.com/hashtag/{m.group(1)}" target="_blank" rel="noopener">#{m.group(1)}</a>', s
    )
    s = _X_MENTION_RE.sub(
        lambda m: f'<a href="https://x.com/{m.group(1)}" target="_blank" rel="noopener">@{m.group(1)}</a>', s
    )
    umap = {u["tco"]: u for u in (urls or []) if u.get("tco")}

    def _u(m: "re.Match[str]") -> str:
        u = umap.get(m.group(0))
        if u and u.get("expanded"):
            return f'<a href="{esc(u["expanded"])}" target="_blank" rel="noopener">{esc(u.get("display") or u["expanded"])}</a>'
        return f'<a href="{esc(m.group(0))}" target="_blank" rel="noopener">{esc(m.group(0))}</a>'

    s = _X_TCO_RE.sub(_u, s)
    return s.replace("\n", "<br>")


def _x_profile_url(handle: str) -> str:
    return f"https://x.com/{handle}"


def _tweet_url(o: Dict[str, Any]) -> str:
    if o.get("url"):
        return o["url"]
    h = (o.get("author") or {}).get("userName") or ""
    return f"{_x_profile_url(h)}/status/{o['id']}" if h and o.get("id") else "#"


def _avatar_img(url: str, cls: str = "x-avatar") -> str:
    if not url:
        return f'<span class="{cls} x-avatar-empty" aria-hidden="true"></span>'
    return f'<img class="{cls}" src="{esc(url)}" loading="lazy" decoding="async" referrerpolicy="no-referrer" alt="">'


def _media_list(o: Dict[str, Any]) -> List[Dict[str, Any]]:
    m = o.get("media")
    if isinstance(m, list):
        return [x for x in m if isinstance(x, dict) and x.get("image")]
    return []


def _has_media(o: Dict[str, Any]) -> bool:
    m = o.get("media")
    return bool(m) if isinstance(m, list) else (isinstance(m, int) and m > 0)


def _x_media_html(o: Dict[str, Any], fallback_url: str, small: bool = False) -> str:
    media = _media_list(o)
    if not media:
        c = o.get("media")
        if isinstance(c, int) and c > 0:
            return (f'<div class="x-media-chip"><a href="{esc(fallback_url)}" target="_blank" rel="noopener">'
                    f'📷 メディア{c if c > 1 else ""}</a></div>')
        return ""
    n = len(media)
    cells = []
    for m in media[:4]:
        link = m.get("link") or fallback_url
        is_video = (m.get("type") or "").lower() in ("video", "animated_gif")
        overlay = '<span class="x-play" aria-hidden="true">▶</span>' if is_video else ""
        cells.append(
            f'<a class="x-media-cell" href="{esc(link)}" target="_blank" rel="noopener">'
            f'<img src="{esc(m["image"])}" loading="lazy" decoding="async" referrerpolicy="no-referrer" alt="">{overlay}</a>'
        )
    more = f'<span class="x-media-more">+{n - 4} 枚</span>' if n > 4 else ""
    cls = f'x-media-grid x-media-{min(n, 4)}' + (' x-media-small' if small else '')
    return f'<div class="{cls}">{"".join(cells)}{more}</div>'


def _render_quote_card(q: Dict[str, Any], ref: Optional[_dt.datetime]) -> str:
    qa = q.get("author") or {}
    qh = qa.get("userName") or ""
    qn = qa.get("name") or qh
    qurl = _tweet_url(q)
    rel, abs_t = _rel_time(q.get("createdAt", ""), ref)
    vcheck = _X_ICO_VERIFIED if qa.get("verified") else ""
    time_bit = (f'<span class="x-sep">·</span><span class="x-quote-time" title="{esc(abs_t)}">{esc(rel)}</span>'
                if rel else "")
    head = (
        f'<div class="x-quote-head">{_avatar_img(qa.get("avatar", ""), "x-avatar-mini")}'
        f'<span class="x-quote-name">{esc(qn)}</span>{vcheck}'
        f'<span class="x-quote-handle">@{esc(qh)}</span>{time_bit}</div>'
    )
    qclean = _clean_tweet_text(q.get("text", ""), q.get("urls"), _has_media(q))
    qtext = (f'<div class="x-quote-text">{linkify_tweet_text(qclean, q.get("urls"))}</div>'
             if qclean.strip() else "")
    qmedia = _x_media_html(q, qurl, small=True)
    open_link = (f'<div class="x-quote-open"><a href="{esc(qurl)}" target="_blank" rel="noopener">X で開く ↗</a></div>'
                 if qurl and qurl != "#" else "")
    return f'<div class="x-quote-card">{head}{qtext}{qmedia}{open_link}</div>'


def _render_tweet_card(
    author: Dict[str, Any], text: str, urls: Any, media_src: Dict[str, Any],
    created: str, url: str, counts: Dict[str, Any], ref: Optional[_dt.datetime],
    reply_to: Optional[str] = None, quote: Optional[Dict[str, Any]] = None,
) -> str:
    handle = author.get("userName") or ""
    name = author.get("name") or handle or "（不明）"
    prof = _x_profile_url(handle)
    rel, abs_t = _rel_time(created, ref)
    vcheck = _X_ICO_VERIFIED if author.get("verified") else ""
    head = (
        f'<div class="x-tweet-head">'
        f'<a class="x-name" href="{esc(prof)}" target="_blank" rel="noopener">{esc(name)}</a>{vcheck}'
        f'<span class="x-handle">@{esc(handle)}</span>'
        f'<span class="x-sep">·</span>'
        f'<a class="x-time" href="{esc(url)}" target="_blank" rel="noopener" title="{esc(abs_t)}">{esc(rel)}</a>'
        f'</div>'
    )
    reply_html = ""
    if reply_to:
        reply_html = (f'<div class="x-replyto">返信先: '
                      f'<a href="{esc(_x_profile_url(reply_to))}" target="_blank" rel="noopener">@{esc(reply_to)}</a> さん</div>')
    has_card = _has_media(media_src) or isinstance(quote, dict)
    clean = _clean_tweet_text(text, urls, has_card)
    text_html = f'<div class="x-text">{linkify_tweet_text(clean, urls)}</div>' if clean.strip() else ""
    media_html = _x_media_html(media_src, url)
    quote_html = _render_quote_card(quote, ref) if isinstance(quote, dict) else ""
    c = counts or {}
    actions = (
        '<div class="x-actions">'
        f'<span class="x-act x-act-reply">{_X_ICO_REPLY}<span class="x-act-n">{_fmt_count(c.get("reply"))}</span></span>'
        f'<span class="x-act x-act-rt">{_X_ICO_RT}<span class="x-act-n">{_fmt_count(c.get("retweet"))}</span></span>'
        f'<span class="x-act x-act-like">{_X_ICO_LIKE}<span class="x-act-n">{_fmt_count(c.get("like"))}</span></span>'
        f'<a class="x-act x-act-link" href="{esc(url)}" target="_blank" rel="noopener" title="X で開く">{_X_ICO_LINK}</a>'
        '</div>'
    )
    return (
        '<div class="x-tweet-row">'
        f'<a class="x-avatar-link" href="{esc(prof)}" target="_blank" rel="noopener">{_avatar_img(author.get("avatar", ""))}</a>'
        f'<div class="x-tweet-main">{head}{reply_html}{text_html}{media_html}{quote_html}{actions}</div>'
        '</div>'
    )


def render_tweet(t: Dict[str, Any], ref: Optional[_dt.datetime]) -> str:
    rt = t.get("retweet_of")
    if isinstance(rt, dict):
        reposter = t.get("author") or {}
        rh = reposter.get("userName") or ""
        rn = reposter.get("name") or rh
        head = (f'<div class="x-repost-line">{_X_ICO_RT}<span>'
                f'<a href="{esc(_x_profile_url(rh))}" target="_blank" rel="noopener">{esc(rn)}</a> がリポスト</span></div>')
        body = _render_tweet_card(
            rt.get("author") or {}, rt.get("text", ""), rt.get("urls"), rt,
            rt.get("createdAt", ""), _tweet_url(rt), t.get("counts") or {}, ref,
        )
        return f'        <article class="x-tweet x-is-repost">{head}{body}</article>'
    reply_to = (t.get("inReplyToUsername") or "") if t.get("isReply") else None
    body = _render_tweet_card(
        t.get("author") or {}, t.get("text", ""), t.get("urls"), t,
        t.get("createdAt", ""), _tweet_url(t), t.get("counts") or {}, ref,
        reply_to=reply_to or None, quote=t.get("quote_of"),
    )
    return f'        <article class="x-tweet">{body}</article>'


def render_x_section(x_data: Dict[str, Any], report_date: str) -> str:
    accounts = x_data.get("accounts") or []
    ref = _parse_x_time(x_data.get("fetched_at", ""))
    shown = [a for a in accounts if (a.get("tweets") or a.get("error"))]
    quiet = [a for a in accounts if not a.get("tweets") and not a.get("error")]
    total = sum(len(a.get("tweets") or []) for a in accounts)
    n_with = len([a for a in accounts if a.get("tweets")])
    fetched_str = f"・取得 {ref.astimezone():%-m/%-d %H:%M}" if ref is not None else ""
    win = x_data.get("window_hours") or 24
    note = f'{n_with} アカウント / {total} 投稿（過去 {win} 時間{esc(fetched_str)}）'

    cards: List[str] = []
    for a in shown:
        handle = a.get("handle", "")
        name = a.get("name") or ""
        avatar = a.get("avatar") or ""
        tweets = a.get("tweets") or []
        err = a.get("error")
        vcheck = _X_ICO_VERIFIED if a.get("verified") else ""
        name_part = f'<span class="x-acc-name">{esc(name)}</span>{vcheck}' if name else ""
        count_html = (f'<span class="x-count">{len(tweets)} 投稿</span>' if tweets
                      else '<span class="x-count x-count-err">取得失敗</span>')
        feed: List[str] = []
        if err:
            feed.append(f'        <p class="x-error">取得失敗: {esc(str(err))}</p>')
        feed += [render_tweet(t, ref) for t in tweets[:_X_MAX_PER_ACCOUNT]]
        if len(tweets) > _X_MAX_PER_ACCOUNT:
            feed.append(f'        <p class="x-more">他に {len(tweets) - _X_MAX_PER_ACCOUNT} 件 — '
                        f'<a href="{esc(_x_profile_url(handle))}" target="_blank" rel="noopener">@{esc(handle)} を X で見る ↗</a></p>')
        feed.append(f'        <p class="x-profile"><a href="{esc(_x_profile_url(handle))}" target="_blank" rel="noopener">'
                    f'@{esc(handle)} のプロフィールを X で開く ↗</a></p>')
        feed.append('        <button type="button" class="collapse-card">▲ 閉じる</button>')
        cards.append(
            f'      <details class="card card-x x-account" id="x-{esc(handle)}">\n'
            f'        <summary class="x-acc-summary">{_avatar_img(avatar, "x-avatar x-acc-avatar")}'
            f'<span class="x-acc-id"><span class="x-acc-line">{name_part}'
            f'<span class="x-acc-handle">@{esc(handle)}</span></span>{count_html}</span>'
            f'<span class="x-acc-caret" aria-hidden="true">▾</span></summary>\n'
            f'        <div class="x-feed">\n' + "\n".join(feed) + "\n        </div>\n"
            f"      </details>"
        )
    quiet_html = ""
    if quiet:
        quiet_html = ('      <p class="x-quiet">投稿なし: '
                      + "、".join(f'<a href="{esc(_x_profile_url(a.get("handle", "")))}" target="_blank" rel="noopener">@{esc(a.get("handle", ""))}</a>'
                                  for a in quiet if a.get("handle"))
                      + "</p>\n")
    if not cards and not quiet_html:
        return ""
    controls = ('<span class="section-controls">'
                '<button type="button" id="x-expand-all">すべて展開</button>'
                '<button type="button" id="x-collapse-all">すべて閉じる</button></span>')
    return (
        '    <section class="section x-section" id="today-x">\n'
        f'      {X_ICON_DEFS}\n'
        f'      <h2 class="section-title">今日のX{controls}</h2>\n'
        f'      <p class="section-note">{note}</p>\n'
        + ("\n".join(cards) + "\n" if cards else "")
        + quiet_html
        + "    </section>\n"
    )


# --- ナビ / ページ骨格 -------------------------------------------------------
def nav_html(date: str, report_dates: List[str]) -> str:
    idx = report_dates.index(date) if date in report_dates else -1
    prev_d = report_dates[idx - 1] if idx > 0 else None
    next_d = report_dates[idx + 1] if 0 <= idx < len(report_dates) - 1 else None
    left = f'<a href="{prev_d}.html" class="nav-prev">{prev_d}</a>' if prev_d else "<span></span>"
    right = f'<a href="{next_d}.html" class="nav-next">{next_d}</a>' if next_d else "<span></span>"
    return (
        '    <nav class="nav">\n'
        f"      {left}\n"
        '      <a href="../index.html">一覧</a>\n'
        f"      {right}\n"
        "    </nav>\n"
    )


def quicklinks_html() -> str:
    """レポート／一覧の先頭に置く外部リンクのバー（TOP_LINKS）。"""
    if not TOP_LINKS:
        return ""
    links = " ".join(
        f'<a href="{esc(url)}" target="_blank" rel="noopener">{esc(label)}</a>'
        for label, url in TOP_LINKS
    )
    return f'    <div class="quicklinks">{links}</div>\n'


def inline_css() -> str:
    if STYLE_CSS.is_file():
        return STYLE_CSS.read_text(encoding="utf-8")
    return ""


PAGE_SCRIPT = """
(function () {
  function openHash() {
    var h = (location.hash || '').replace('#', '');
    if (!h) return;
    var el = document.getElementById(h);
    if (el && el.tagName === 'DETAILS') {
      el.open = true;
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
  window.addEventListener('hashchange', openHash);
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('a[href^="#card-"]').forEach(function (a) {
      a.addEventListener('click', function () {
        var el = document.getElementById(a.getAttribute('href').slice(1));
        if (el && el.tagName === 'DETAILS') el.open = true;
      });
    });
    document.querySelectorAll('button.collapse-card').forEach(function (b) {
      b.addEventListener('click', function () {
        var d = b.closest('details');
        if (!d) return;
        d.open = false;
        // CSS の scroll-behavior:smooth を一時無効化して即スナップ
        var root = document.documentElement, prev = root.style.scrollBehavior;
        root.style.scrollBehavior = 'auto';
        d.scrollIntoView({ block: 'start', behavior: 'instant' });
        root.style.scrollBehavior = prev;
      });
    });
    function wire(btnId, selector, open) {
      var b = document.getElementById(btnId);
      if (b) b.addEventListener('click', function () {
        document.querySelectorAll(selector).forEach(function (d) { d.open = open; });
      });
    }
    wire('expand-all', 'details.domain-details', true);
    wire('collapse-all', 'details.domain-details', false);
    wire('x-expand-all', 'details.x-account', true);
    wire('x-collapse-all', 'details.x-account', false);
    openHash();
  });
})();
""".strip()


def build_report_html(date: str, report_dates: List[str]) -> Optional[str]:
    integ = find_integration(date)
    if integ is None:
        print(f"  ! {date}: 統合レポート (_integrations/{date}_*.md) が無いためスキップ", file=sys.stderr)
        return None
    h1, sections, _ = split_h1_sections(integ.read_text(encoding="utf-8"))
    page_title = h1 or f"デイリーレポート {date}"

    # トピック表からドメイン→GitHubリンクの対応を作る
    topic_rows: List[Tuple[str, str, str]] = []
    topic_links: Dict[str, str] = {}
    for head, body in sections:
        if "トピック" in head:
            topic_rows = parse_topic_table(body)
            for key, _theme, link in topic_rows:
                if key in DOMAIN_KEYS and link:
                    topic_links[key] = link
            break

    def is_overview_head(h: str) -> bool:
        return "テーマ概要" in h or ("概要" in h and "蓄積" not in h and "スナップショット" not in h)

    # テーマ概要
    theme_overview: Dict[str, str] = {}
    for head, body in sections:
        if is_overview_head(head):
            parsed = parse_theme_overview(body)
            if parsed:
                theme_overview = parsed
                break

    body_parts: List[str] = []
    used_anchors = {"topics", "domains", "next-actions"}

    def uniq(anchor: str) -> str:
        a, k = anchor, 2
        while a in used_anchors:
            a, k = f"{anchor}-{k}", k + 1
        used_anchors.add(a)
        return a

    used_overview = False
    for idx, (head, body) in enumerate(sections):
        if "トピック" in head:
            continue  # トピック一覧テーブルは出さない（テーマ概要カードが代替し、リンクは↑で取得済み）
        elif is_overview_head(head) and not used_overview:
            cards = render_domain_cards(theme_overview, topic_links, date)
            body_parts.append(cards or render_generic_section(head, body, uniq("domains-fb")))
            used_overview = True
        elif "蓄積" in head or "スナップショット" in head:
            body_parts.append(render_generic_section(head, body, uniq("accumulation")))
        elif "横断" in head:
            body_parts.append(render_box_section(head, body, "insight", uniq("patterns")))
        elif "接続" in head:
            body_parts.append(render_box_section(head, body, "connection", uniq("connections")))
        elif "洞察" in head:
            body_parts.append(render_box_section(head, body, "insight", uniq("insights")))
        elif "アクション" in head or "指令" in head:
            body_parts.append(render_actions_section(head, body))
        else:
            slug = re.sub(r"[^a-z0-9]+", "-", head.lower()).strip("-")
            body_parts.append(render_generic_section(head, body, uniq(f"sec-{idx}-{slug}" if slug else f"sec-{idx}")))

    # テーマ概要セクションが統合レポートに無くてもカードは先頭に出す
    if not used_overview:
        cards = render_domain_cards(theme_overview, topic_links, date)
        if cards:
            body_parts.insert(0, cards)

    x_data = load_x_data(date)
    x_section = render_x_section(x_data, date) if x_data else ""

    css = inline_css()
    html_doc = f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{esc(page_title)}</title>
  <style>
{css}
  </style>
</head>
<body>
  <div class="container">
{quicklinks_html()}{nav_html(date, report_dates)}    <header class="report-header">
      <h1>デイリーレポート</h1>
      <div class="report-date">{esc(date)}</div>
    </header>
{x_section}{''.join(body_parts)}    <footer class="footer">
      <p><em>{esc(GENERATED_BY)}</em></p>
    </footer>
  </div>
  <script>
{PAGE_SCRIPT}
  </script>
</body>
</html>
"""
    return html_doc


# --- index.html --------------------------------------------------------------
def topics_summary_for(date: str) -> str:
    """index 用：その日のトピック（テーマ名）をカンマ区切りで。"""
    integ = find_integration(date)
    themes: List[str] = []
    if integ is not None:
        _h1, sections, _ = split_h1_sections(integ.read_text(encoding="utf-8"))
        for head, body in sections:
            if "トピック" in head:
                for _key, theme, _link in parse_topic_table(body):
                    if theme:
                        themes.append(theme)
                break
    if not themes:
        for key in DOMAIN_KEYS:
            e = find_domain_entry(key, date)
            if e:
                t, _tags, _b = parse_domain_entry(e)
                themes.append(t)
    return "、".join(themes)


def build_index_html(report_dates: List[str]) -> str:
    css = inline_css()
    items = []
    for d in sorted(report_dates, reverse=True):
        topics = esc(topics_summary_for(d))
        items.append(
            f'      <li><a href="reports/{d}.html">\n'
            f'        <span class="report-list-date">{d}</span>\n'
            f'        <span class="report-list-topics">{topics}</span>\n'
            f"      </a></li>"
        )
    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>知識統合システム — デイリーレポート</title>
  <style>
{css}
  </style>
</head>
<body>
  <div class="container">
{quicklinks_html()}    <div class="index-header">
      <h1>知識統合システム</h1>
      <p>多重影分身・日次学習レポート</p>
    </div>
    <ul class="report-list">
{chr(10).join(items)}
    </ul>
    <div class="footer">
      <p><em>{esc(GENERATED_BY)}</em></p>
    </div>
  </div>
</body>
</html>
"""


# --- メイン ------------------------------------------------------------------
def today_str() -> str:
    try:
        out = subprocess.run(["date", "+%Y-%m-%d"], capture_output=True, text=True, check=True)
        s = out.stdout.strip()
        if DATE_RE.fullmatch(s):
            return s
    except Exception:
        pass
    return _dt.date.today().isoformat()


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: List[str]) -> int:
    args = [a for a in argv[1:] if a]
    backfill_all = "--all" in args
    date_args = [a for a in args if not a.startswith("-")]

    if backfill_all:
        target_dates = all_integration_dates()
        if not target_dates:
            sys.exit("エラー: _integrations/ にレポートが見つかりません。")
    else:
        date = date_args[0] if date_args else today_str()
        if not DATE_RE.fullmatch(date):
            sys.exit(f"エラー: 日付は YYYY-MM-DD 形式で指定してください（受け取った値: {date!r}）。")
        target_dates = [date]

    # 生成対象 = 指定日 ∪ 既に docs/reports/ にある日（ナビ整合のため再生成）
    report_dates = sorted(set(existing_report_dates()) | set(target_dates))

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    # GitHub Pages の Jekyll 処理を無効化（手組みの静的 HTML をそのまま配信させる）
    nojekyll = DOCS_DIR / ".nojekyll"
    if not nojekyll.exists():
        nojekyll.touch()

    written = []
    final_dates = []
    for d in report_dates:
        doc = build_report_html(d, report_dates)
        if doc is None:
            # 統合レポートが無い → 既存 .html があればそのまま残す
            if (REPORTS_DIR / f"{d}.html").is_file():
                final_dates.append(d)
            continue
        if write_if_changed(REPORTS_DIR / f"{d}.html", doc):
            written.append(f"docs/reports/{d}.html")
        final_dates.append(d)

    # ナビが report_dates 前提で生成されているので、欠けがあった場合に備えてもう一周（軽量）
    if set(final_dates) != set(report_dates):
        for d in final_dates:
            doc = build_report_html(d, final_dates)
            if doc and write_if_changed(REPORTS_DIR / f"{d}.html", doc):
                if f"docs/reports/{d}.html" not in written:
                    written.append(f"docs/reports/{d}.html")

    if write_if_changed(DOCS_DIR / "index.html", build_index_html(final_dates)):
        written.append("docs/index.html")

    if written:
        print("生成/更新:")
        for w in written:
            print(f"  - {w}")
    else:
        print("変更なし（生成済みと同一）。")
    print(f"レポート総数: {len(final_dates)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
