#!/bin/bash
# ============================================
# daily_run.sh - 毎朝6時に実行
#   RUN_LEARN=1 … 各ドメインの学習(/learn)＋レポート＋X＋公開（フル運用）
#   RUN_LEARN=0 … 学習を休止し、X ダイジェストの収集・公開のみ（下部の切替フラグ）
# ============================================

set -euo pipefail

export PATH="/Users/nao/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
set -a
source "$PROJECT_DIR/config/.env"
set +a
LOG_DIR="$PROJECT_DIR/data/logs"
DATE=$(date +%Y-%m-%d)
LOGFILE="$LOG_DIR/daily_${DATE}.log"

mkdir -p "$LOG_DIR"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOGFILE"
}

cd "$PROJECT_DIR"

# 気になる人の直近ツイートを取得（data/x/<DATE>.json）。失敗しても /learn は止めない
log "=== X 取得 ==="
if python3 "$PROJECT_DIR/scripts/fetch_x.py" "$DATE" >> "$LOGFILE" 2>&1; then
  log "=== X 取得 完了 ==="
else
  log "=== X 取得 失敗（続行・exit $?）==="
fi

# ============================================================
# 学習モード切り替え（学習を再開するときは 1 に戻すだけ）
#   1 → 各ドメインの学習(/learn)をフル実行
#   0 → 学習を休止し、冒頭で収集した X ダイジェストの公開のみ
# ============================================================
RUN_LEARN=0

if [ "$RUN_LEARN" = "1" ]; then
  log "=== /learn 起動 ==="
  if claude -p "/learn" \
    --add-dir "$PROJECT_DIR" \
    --permission-mode bypassPermissions \
    >> "$LOGFILE" 2>&1; then
    log "=== /learn 完了 ==="
  else
    log "=== /learn でエラー発生（exit code $?）==="
    exit 1
  fi

  # 当日エントリのネタ被り監査（実ファイルから台帳を再構築 → 当日衝突をチェック）。
  # 監視目的。重複を検出しても日次実行は失敗させない。
  log "=== ネタ被り監査 ==="
  python3 "$PROJECT_DIR/scripts/build_ledger.py" >> "$LOGFILE" 2>&1 || log "build_ledger スキップ（exit $?）"
  if python3 "$PROJECT_DIR/scripts/audit_ledger.py" --new "$DATE" >> "$LOGFILE" 2>&1; then
    log "=== 監査: 当日エントリに既習との衝突なし ==="
  else
    log "=== ⚠ 監査: 当日エントリが既習トピックと衝突（上のログ参照・要確認）==="
  fi

  # 週次（月曜）は全期間の重複サマリーもログに残す
  if [ "$(date +%u)" -eq 1 ]; then
    log "=== 週次フル重複監査 ==="
    python3 "$PROJECT_DIR/scripts/audit_ledger.py" >> "$LOGFILE" 2>&1 || true
  fi
else
  # --- 学習休止中: X ダイジェストのみ公開（LLM は呼ばない） -----------------------
  log "=== 学習休止中（RUN_LEARN=0）: X ダイジェストのみ公開 ==="

  # build_report_html.py はその日の統合レポート(_integrations/<DATE>_*.md)が無いと
  # ページを生成しないため、最小限の枠だけ用意する（学習内容は無し＝X セクションのみ）。
  REPORT_MD="$PROJECT_DIR/_integrations/${DATE}_デイリーレポート.md"
  if [ ! -f "$REPORT_MD" ]; then
    cat > "$REPORT_MD" <<EOF
# デイリーレポート ${DATE}

各ドメインの学習は現在休止中。本日は気になる人の X ダイジェストのみを公開する。

*Generated by 知識統合システム（X ダイジェストモード）*
EOF
    log "  最小レポート枠を作成: _integrations/${DATE}_デイリーレポート.md"
  fi

  log "=== レポート HTML 生成 ==="
  python3 "$PROJECT_DIR/scripts/build_report_html.py" "$DATE" >> "$LOGFILE" 2>&1 || log "build_report_html 失敗（exit $?）"

  log "=== Git コミット & プッシュ ==="
  git add "$REPORT_MD" "$PROJECT_DIR/docs" >> "$LOGFILE" 2>&1 || true
  if git diff --cached --quiet; then
    log "=== コミット対象なし ==="
  else
    git commit -m "🐦 X ダイジェスト ${DATE}" >> "$LOGFILE" 2>&1 || true
    git push >> "$LOGFILE" 2>&1 || log "push 失敗（exit $?）"
    log "=== 公開完了: https://yamamotonaoyuki.github.io/DailyLearning/reports/${DATE}.html ==="
  fi
fi
